apiVersion: v1
kind: ConfigMap
metadata:
  name: rs-news-dev-config
data:
  redis_port: "6379"
  redis_host: "gcr-rs-dev-workshop-redis-cluster.ul87r8.0001.use2.cache.amazonaws.com"
  messge_broker_redis_port: "6379"
  messge_broker_redis_host: "redis-cart"
  aws_region: "us-east-2"
  s3_bucket: "aws-gcr-rs-sol-dev-workshop-us-east-2-472383854665"
  s3_prefix: "sample-data-news"
  click_record_file_path: 'sample-data-news/system/ingest-data/action/'
  user_record_file_path: 'sample-data-news/system/ingest-data/user/'
  click_record_bucket: 'aws-gcr-rs-sol-dev-workshop-us-east-2-472383854665'
  local_data_folder: '/rs-data/news-dev/'

  
